packages:
  - "apps/*"
  - "packages/*"
  - "tools/*"
minimumReleaseAgeExclude:
  - "@types/react-dom@19.2.3"
  - "@types/react@19.2.17"
  - playwright@1.61.1
  - pixi.js@8.19.0
  - react-dom@19.2.7
  - react@19.2.7
  - "@typescript-eslint/eslint-plugin@8.62.0"
  - "@typescript-eslint/parser@8.62.0"
  - "@typescript-eslint/project-service@8.62.0"
  - "@typescript-eslint/scope-manager@8.62.0"
  - "@typescript-eslint/tsconfig-utils@8.62.0"
  - "@typescript-eslint/type-utils@8.62.0"
  - "@typescript-eslint/types@8.62.0"
  - "@typescript-eslint/typescript-estree@8.62.0"
  - "@typescript-eslint/utils@8.62.0"
  - "@typescript-eslint/visitor-keys@8.62.0"
  - typescript-eslint@8.62.0
  - vite@8.1.0
  - playwright-core@1.61.1
