import { defineWorkspaceSmoke, type WorkspaceSmoke } from "@wuming-town/foundation";

export { formatUint32Hex, hashStringToUint32, mixUint32 } from "./deterministic-hash";
export {
  DEFAULT_WALK_COST_MILLI,
  MAP_DIRECTION_EAST,
  MAP_DIRECTION_MASK_CARDINAL,
  MAP_DIRECTION_MASK_EAST,
  MAP_DIRECTION_MASK_NORTH,
  MAP_DIRECTION_MASK_SOUTH,
  MAP_DIRECTION_MASK_WEST,
  MAP_DIRECTION_NORTH,
  MAP_DIRECTION_SOUTH,
  MAP_DIRECTION_WEST,
  MAP_GRID_SNAPSHOT_VERSION,
  MAP_TERRAIN_BLOCKED,
  MapGrid,
  createMapGrid,
} from "./map-grid";
export {
  REGION_ROOM_REBUILD_SNAPSHOT_VERSION,
  RegionRoomRebuilder,
  createRegionRoomRebuilder,
} from "./region-room-rebuild";
export {
  GridPathfinder,
  PathRequestBatcher,
  createGridPathfinder,
  createPathRequestBatcher,
  createPathVersionBasis,
  resolveTopKPathCandidates,
  samePathBasis,
} from "./pathing";
export {
  WORK_OFFER_NONE,
  ReasonTraceStore,
  WorkOfferIndex,
  createReasonTraceStore,
  createWorkOfferIndex,
} from "./work-offers";
export {
  M3_NEED_STORE_SNAPSHOT_VERSION,
  NEED_ACTOR_NONE,
  NEED_LANE_COMFORT,
  NEED_LANE_COUNT,
  NEED_LANE_HUNGER,
  NEED_LANE_REST,
  NEED_LANE_SAFETY,
  NEED_LANE_SOCIAL,
  NEED_URGENCY_BUCKET_COUNT,
  NEED_URGENCY_DEFAULT_CANDIDATE_CAP,
  NEED_URGENCY_DEFAULT_SELECTED_CAP,
  NEED_VALUE_MAX,
  NEED_VALUE_MIN,
  NeedStore,
  NeedUrgencyIndex,
  NeedUrgencyTraceStore,
  calculateNeedUrgencyBucket,
  createNeedStore,
  createNeedUrgencyIndex,
  createNeedUrgencyTraceStore,
} from "./m3-needs";
export {
  M3_MOOD_ACTOR_NONE,
  M3_MOOD_BASELINE,
  M3_MOOD_DEFAULT_MEMORY_CAPACITY,
  M3_MOOD_DEFAULT_THOUGHT_CAPACITY,
  M3_MOOD_DEFAULT_TRACE_CAPACITY,
  M3_MOOD_LANE_COUNT,
  M3_MOOD_LANE_ENERGY,
  M3_MOOD_LANE_TENSION,
  M3_MOOD_LANE_VALENCE,
  M3_MOOD_THOUGHT_MEMORY_SNAPSHOT_VERSION,
  M3_MOOD_VALUE_MAX,
  M3_MOOD_VALUE_MIN,
  M3MoodReasonTraceStore,
  MoodThoughtMemoryStore,
  createM3MoodReasonTraceStore,
  createMoodThoughtMemoryStore,
} from "./m3-mood-thoughts";
export {
  JOB_CORE_SNAPSHOT_VERSION,
  JOB_NONE,
  JobCoreStore,
  createJobCoreHashFields,
  createJobCoreStore,
  restoreJobCoreStore,
} from "./job-core";
export {
  ITEM_STACK_SNAPSHOT_VERSION,
  ItemStackStore,
  createItemStackStore,
} from "./item-stack-store";
export { StorageLogisticsIndex, createStorageLogisticsIndex } from "./storage-logistics-index";
export { HAULING_JOB_KIND, HaulingJobStore, createHaulingJobStore } from "./hauling-jobs";
export {
  BUILD_SITE_CONSTRUCTION_JOB_KIND,
  BUILD_SITE_DELIVERY_JOB_KIND,
  BUILD_SITE_LANTERN_STATE_UNLIT_PENDING_FUEL,
  BuildSiteStore,
  createBuildSiteStore,
  mapPathFailure,
} from "./build-site";
export {
  HAULING_BUILDING_SCENARIO_ID,
  M1_BLUEPRINT_ROAD_LANTERN_FRAME,
  M1_BUILDING_ROAD_LANTERN_FRAME,
  M1_ITEM_PAPER,
  M1_ITEM_STONE,
  M1_ITEM_WOOD,
  runHaulingBuildingScenario,
} from "./hauling-building-scenario";
export {
  M1_COMMAND_PREFIX,
  M1_READ_MODEL_HASH_VERSION,
  M1_SAVE_FORMAT_VERSION,
  M1_SAVE_MAGIC,
  M1_SECTION_DIRECTORY_VERSION,
  M1_SECTION_VERSION,
  compareM1ReplayRuns,
  createM1AdvanceCommandId,
  createM1HaulingBuildingSaveEnvelope,
  createM1ReadOnlyProjection,
  loadM1HaulingBuildingSaveEnvelope,
  parseM1AdvanceCommandId,
  resumeM1HaulingBuildingFromSave,
  runM1HaulingBuildingReplay,
} from "./m1-save-replay";
export {
  M2_COMMAND_PREFIX,
  M2_READ_MODEL_HASH_VERSION,
  M2_SAVE_FORMAT_VERSION,
  M2_SAVE_MAGIC,
  M2_SECTION_DIRECTORY_VERSION,
  M2_SECTION_VERSION,
  compareM2ReplayRuns,
  createM2AdvanceCommandId,
  createM2ReadOnlyProjection,
  createM2WorkLogisticsSaveEnvelope,
  loadM2WorkLogisticsSaveEnvelope,
  parseM2AdvanceCommandId,
  resumeM2WorkLogisticsFromSave,
  runM2WorkLogisticsReplay,
} from "./m2-save-replay";
export {
  M2_BLUEPRINT_ROAD_LANTERN_FRAME,
  M2_BUILDING_ROAD_LANTERN_FRAME,
  M2_ITEM_BINDING_PAPER,
  M2_ITEM_STONE,
  M2_ITEM_WOOD,
  M2_WORK_LOGISTICS_SCENARIO_ID,
  runM2WorkLogisticsScenario,
} from "./m2-work-logistics-scenario";
export {
  M3_ABILITY_COMMUNICATION,
  M3_ABILITY_CONSCIOUSNESS,
  M3_ABILITY_LANE_COUNT,
  M3_ABILITY_MANIPULATION,
  M3_ABILITY_MOVEMENT,
  M3_ABILITY_SIGHT,
  M3_ABILITY_STAMINA,
  M3_HEALTH_CONDITION_ACTIVE,
  M3_HEALTH_CONDITION_KIND_ILLNESS,
  M3_HEALTH_CONDITION_KIND_INJURY,
  M3_HEALTH_CONDITION_RECOVERING,
  M3_HEALTH_CONDITION_REMOVED,
  M3_HEALTH_CONDITION_RESOLVED,
  M3_HEALTH_SNAPSHOT_VERSION,
  M3AbilityCacheStore,
  M3HealthConditionStore,
  createM3AbilityCacheStore,
  createM3HealthAbilityMask,
  createM3HealthConditionStore,
} from "./m3-health";
export {
  LOCATION_CONTAINER,
  LOCATION_MAP,
  LOCATION_NONE,
  LocationStore,
  createLocationStore,
} from "./location-store";
export {
  RESERVATION_CAPACITY,
  RESERVATION_CELL,
  RESERVATION_ENTITY,
  RESERVATION_INTERACTION_SPOT,
  RESERVATION_ITEM_QUANTITY,
  RESERVATION_LEDGER_SNAPSHOT_VERSION,
  ReservationLedger,
  createReservationLedger,
  restoreReservationLedger,
} from "./reservation-ledger";
export { createMapGridHashFields } from "./map-grid-hash";
export {
  NamedRandomStreams,
  RANDOM_STREAMS_SNAPSHOT_VERSION,
  createNamedRandomStreams,
  restoreNamedRandomStreams,
} from "./deterministic-rng";
export {
  DayNightStore,
  M3EnvironmentDirtyQueue,
  M3EnvironmentStore,
  WeatherStore,
  createM3EnvironmentStore,
  runM3EnvironmentReplay,
} from "./m3-environment";
export {
  M3_REST_DEFAULT_CANDIDATE_CAP,
  M3_REST_DEFAULT_EXACT_PATH_CAP,
  M3_REST_DEFAULT_SELECTED_CAP,
  M3_REST_EMERGENCY_THRESHOLD,
  M3_REST_FIXTURE_NONE,
  M3_REST_SLEEP_JOB_KIND,
  M3_REST_SLEEP_STORE_VERSION,
  M3_REST_SLEEP_TRACE_CAPACITY,
  M3_REST_URGENCY_THRESHOLD,
  RestCandidateIndex,
  RestJobDriverStore,
  RestSleepStore,
  RestSleepTraceStore,
  createRestCandidateIndex,
  createRestJobDriverStore,
  createRestSleepStore,
  createRestSleepTraceStore,
  selectPathResolvedRestFixture,
} from "./m3-rest-sleep";
export {
  M3_FOOD_DEFAULT_CANDIDATE_CAP,
  M3_FOOD_DEFAULT_EXACT_PATH_CAP,
  M3_FOOD_DEFAULT_SELECTED_CAP,
  M3_FOOD_STACK_NONE,
  M3FoodAvailabilityStore,
  createM3FoodAvailabilityStore,
  resolveM3FoodPathCandidate,
} from "./m3-food";
export {
  M3_EATING_JOB_KIND,
  M3EatingJobDriverStore,
  calculateM3FoodConservationTotal,
  createM3EatingJobDriverStore,
} from "./m3-eating-jobs";
export {
  DEFAULT_M3_SCHEDULE_WINDOWS,
  M3_ENVIRONMENT_OWNER_VERSION,
  M3_WEATHER_INTERVAL_TICKS,
  M3_WEATHER_STREAM_ID,
  chooseScheduledWeather,
  createDefaultM3ScheduleWindows,
  getWeatherSeverity,
} from "./m3-environment-data";
export { compareReplayCheckpoints } from "./replay-diagnostics";
export {
  CANONICAL_WORLD_HASH_VERSION,
  formatCanonicalWorldHash,
  hashCanonicalWorld,
} from "./world-hash";
export { Int32ComponentStore, createInt32ComponentStore } from "./component-store";
export {
  EntityRegistry,
  MAX_ENTITY_GENERATION,
  createEntityRegistry,
  sameEntity,
} from "./entity-id";
export { SpatialIndex, createSpatialIndex } from "./spatial-index";
export {
  HEADLESS_SUMMARY_VERSION,
  HEADLESS_SNAPSHOT_VERSION,
  advanceHeadlessTicks,
  createHeadlessReplayCheckpoint,
  createHeadlessRunner,
  queueHeadlessCommand,
  restoreHeadlessRunner,
  runHeadlessTicks,
  serializeHeadlessRunner,
  setHeadlessPaused,
  setHeadlessSpeed,
  stepHeadlessFrames,
  summarizeHeadlessRun,
} from "./runner";
export {
  StructuralCommandBuffer,
  createStructuralCommandBuffer,
  createStructuralCommandResultView,
  readStructuralCommandResult,
} from "./structural-commands";
export type {
  ComponentReadResult,
  ComponentStoreReason,
  ComponentStoreResult,
  Int32ComponentStoreOptions,
} from "./component-store";
export type {
  EntityAllocationResult,
  EntityDestroyResult,
  EntityId,
  EntityRegistryOptions,
  EntityRegistryReason,
  EntityValidationResult,
} from "./entity-id";
export { TICKS_PER_DAY, TICKS_PER_SECOND, isSafeTick, requireSafeTick } from "./time";
export type {
  HeadlessCommandInput,
  HeadlessQueuedCommand,
  HeadlessRunnerSnapshot,
  HeadlessRunSummary,
  HeadlessRunnerOptions,
  HeadlessRunnerState,
  QueueCommandResult,
} from "./runner";
export type {
  QueueStructuralCommandResult,
  StructuralCommandKind,
  StructuralCommandReason,
  StructuralCommandResult,
  StructuralCommandResultView,
  StructuralCommitReport,
} from "./structural-commands";
export type {
  NamedRandomStreamsOptions,
  RandomStreamSnapshot,
  RandomStreamsSnapshot,
} from "./deterministic-rng";
export type {
  M3DayNightProjection,
  M3EnvironmentCheckpoint,
  M3EnvironmentCommand,
  M3EnvironmentDirtyKey,
  M3EnvironmentMetrics,
  M3EnvironmentProjection,
  M3EnvironmentReason,
  M3EnvironmentReplayResult,
  M3ScheduleWindowDefinition,
  M3ScheduleWindowId,
  M3WeatherKind,
  M3WeatherProjection,
  M3WeatherSeverityLanes,
} from "./m3-environment-data";
export type {
  RestCandidateIndexOptions,
  RestCandidateQuery,
  RestCandidateQueryResult,
  RestFixtureInput,
  RestFixtureKind,
  RestFixtureView,
  RestFixtureWeatherExposure,
  RestJobCreateInput,
  RestJobDriverSnapshot,
  RestJobStep,
  RestJobView,
  RestKind,
  RestSelectionInput,
  RestSelectionResult,
  RestSleepMetrics,
  RestSleepMutationResult,
  RestSleepReason,
  RestTraceInput,
  RestTraceView,
} from "./m3-rest-sleep";
export type {
  M3FoodCandidateQuery,
  M3FoodCandidateQueryResult,
  M3FoodMetrics,
  M3FoodMutationResult,
  M3FoodPathSelectionOptions,
  M3FoodPathSelectionResult,
  M3FoodPortionInput,
  M3FoodPortionView,
  M3FoodReason,
} from "./m3-food";
export type {
  M3EatingJobCreateInput,
  M3EatingJobView,
  M3EatingMetrics,
  M3EatingMutationResult,
  M3EatingReason,
  M3EatingStep,
} from "./m3-eating-jobs";
export type { RunnerSpeed, Tick } from "./time";
export type {
  ReplayCheckpoint,
  ReplayComparisonResult,
  ReplayDivergence,
  ReplayDivergenceReason,
} from "./replay-diagnostics";
export type {
  CanonicalCommandEntry,
  CanonicalWorldField,
  CanonicalWorldHashInput,
} from "./world-hash";
export type {
  MapCellReadResult,
  MapCellIndexReadResult,
  MapCellUpdate,
  MapCellUpdateResult,
  MapCellView,
  MapDirtyProcessResult,
  MapGridOptions,
  MapGridReason,
  MapGridSnapshot,
  MapMovementResult,
} from "./map-grid";
export type {
  RegionGraphBasis,
  RegionRoomCellBasis,
  RegionRoomMarkResult,
  RegionRoomMetrics,
  RegionRoomMutationResult,
  RegionRoomProcessResult,
  RegionRoomReason,
  RegionRoomSnapshot,
} from "./region-room-rebuild";
export type {
  PathBatchProcessResult,
  PathBatcherMetrics,
  PathCandidate,
  PathCommitResult,
  PathEnqueueResult,
  PathReason,
  PathRequest,
  PathSearchResult,
  PathVersionBasis,
  TopKPathResolutionOptions,
  TopKPathResolutionResult,
} from "./pathing";
export type {
  ReasonTraceStoreMetrics,
  WorkOfferIndexMetrics,
  WorkOfferIndexOptions,
  WorkOfferInput,
  WorkOfferMutationResult,
  WorkOfferQuery,
  WorkOfferQueryResult,
  WorkOfferReason,
  WorkOfferReasonTraceInput,
  WorkOfferReasonTraceView,
  WorkOfferSelectionOptions,
  WorkOfferSelectionResult,
  WorkOfferTraceReason,
} from "./work-offers";
export type {
  NeedActorInput,
  NeedActorView,
  NeedChangeInput,
  NeedChangeReason,
  NeedDirtySink,
  NeedLastChangeView,
  NeedLane,
  NeedMutationResult,
  NeedReason,
  NeedScheduleResult,
  NeedStoreMetrics,
  NeedStoreOptions,
  NeedUrgencyIndexMetrics,
  NeedUrgencyIndexOptions,
  NeedUrgencyQuery,
  NeedUrgencyQueryResult,
  NeedUrgencyTraceInput,
  NeedUrgencyTraceMetrics,
  NeedUrgencyTraceReason,
  NeedUrgencyTraceView,
} from "./m3-needs";
export type {
  M3MoodActorView,
  M3MoodLane,
  M3MoodMetrics,
  M3MoodMutationResult,
  M3MoodReason,
  M3MoodRowView,
  M3MoodSourceKind,
  M3MoodStoreOptions,
  M3MoodThoughtInput,
  M3MoodTraceInput,
  M3MoodTraceMetrics,
  M3MoodTraceView,
  M3MoodUpdateResult,
} from "./m3-mood-thoughts";
export type {
  JobCoreMetrics,
  JobCoreMutationResult,
  JobCoreReason,
  JobCoreSnapshot,
  JobCoreSnapshotInput,
  JobCoreStoreOptions,
  JobCreateInput,
  JobDriverStep,
  JobFailureReason,
  JobInterruptResult,
  JobInterruptionKind,
  JobInterruptionPolicy,
  JobRecordSnapshot,
  JobRecordView,
  JobSnapshotResult,
  JobStatus,
  JobTerminalResult,
  JobTickResult,
} from "./job-core";
export type {
  ItemStackCreateInput,
  ItemStackMetrics,
  ItemStackMutationResult,
  ItemStackReason,
  ItemStackView,
} from "./item-stack-store";
export type {
  StorageLogisticsMetrics,
  StorageLogisticsMutationResult,
  StorageLogisticsReason,
  StorageSlotInput,
  StorageSlotView,
} from "./storage-logistics-index";
export type {
  HaulingJobCreateInput,
  HaulingJobView,
  HaulingMetrics,
  HaulingMutationResult,
  HaulingReason,
  HaulingStep,
} from "./hauling-jobs";
export type {
  BuildSiteBuildJobInput,
  BuildSiteBuildReservationInput,
  BuildSiteCompletionResult,
  BuildSiteCreateInput,
  BuildSiteDeliveryJobInput,
  BuildSiteJobResult,
  BuildSiteJobStep,
  BuildSiteJobView,
  BuildSiteMetrics,
  BuildSiteMutationResult,
  BuildSiteReason,
  BuildSiteReservationInput,
  BuildSiteView,
} from "./build-site";
export type {
  HaulingBuildingCounters,
  HaulingBuildingEndState,
  HaulingBuildingFailureReasons,
  HaulingBuildingInvariants,
  HaulingBuildingScenarioOptions,
  HaulingBuildingScenarioSummary,
} from "./hauling-building-scenario";
export type {
  M1CommandLogTailSection,
  M1EntityStoresSection,
  M1HaulingBuildingSaveEnvelope,
  M1HaulingBuildingSaveSections,
  M1JobsReservationsSection,
  M1MapChunksSection,
  M1RandomStreamsSection,
  M1ReadOnlyProjection,
  M1RenderSnapshotProjection,
  M1ReplayArtifactPaths,
  M1ReplayCheckpoint,
  M1ReplayComparison,
  M1ReplayOptions,
  M1ReplayResult,
  M1ReplayRun,
  M1ResumeOptions,
  M1SaveEnvelopeResult,
  M1SaveLoadResult,
  M1SaveReplayReason,
  M1UiDetailProjection,
} from "./m1-save-replay";
export type {
  M2BuildOrderRecord,
  M2CommandLogTailSection,
  M2EntityStoresSection,
  M2ItemStackRecord,
  M2JobReservationRecord,
  M2JobsReservationsSection,
  M2MapChunksSection,
  M2OrderReadModelProjection,
  M2OwnerHandle,
  M2RandomStreamsSection,
  M2ReadOnlyProjection,
  M2RebuiltIndexesProjection,
  M2RenderSnapshotProjection,
  M2ReplayArtifactPaths,
  M2ReplayCheckpoint,
  M2ReplayComparison,
  M2ReplayOptions,
  M2ReplayResult,
  M2ReplayRun,
  M2ResumeOptions,
  M2SaveEnvelopeResult,
  M2SaveLoadResult,
  M2SaveReplayReason,
  M2WorkLogisticsSaveEnvelope,
  M2WorkLogisticsSaveSections,
} from "./m2-save-replay";
export type {
  M2WorkLogisticsCounters,
  M2WorkLogisticsEndState,
  M2WorkLogisticsFailureReasons,
  M2WorkLogisticsInvariants,
  M2WorkLogisticsScenarioOptions,
  M2WorkLogisticsScenarioSummary,
} from "./m2-work-logistics-scenario";
export type {
  M3AbilityMetrics,
  M3AbilityQueryResult,
  M3AbilityReason,
  M3AbilityCacheStoreOptions,
  M3HealthConditionInput,
  M3HealthConditionMutationResult,
  M3HealthConditionReason,
  M3HealthConditionStoreOptions,
  M3HealthConditionUpdateInput,
  M3HealthConditionView,
  M3HealthMetrics,
} from "./m3-health";
export type {
  LocationCleanupReason,
  LocationDestroyResult,
  LocationKind,
  LocationLifecycleHooks,
  LocationMutationResult,
  LocationReadResult,
  LocationStoreMetrics,
  LocationStoreOptions,
  LocationStoreReason,
  LocationView,
} from "./location-store";
export type {
  ReservationAcquireResult,
  ReservationChannel,
  ReservationChannelCode,
  ReservationClaimRequest,
  ReservationLedgerMetrics,
  ReservationLedgerOptions,
  ReservationLedgerSnapshot,
  ReservationLedgerSnapshotInput,
  ReservationReason,
  ReservationRecordSnapshot,
  ReservationRecordView,
  ReservationReleaseResult,
  ReservationTransactionRequest,
} from "./reservation-ledger";
export type {
  SpatialIndexMetrics,
  SpatialIndexMutationResult,
  SpatialIndexOptions,
  SpatialIndexQueryResult,
  SpatialIndexReason,
} from "./spatial-index";

export const SIM_CORE_SMOKE: WorkspaceSmoke = defineWorkspaceSmoke(
  "@wuming-town/sim-core",
  "package",
);

export const SIM_CORE_ALLOWED_INPUTS: readonly string[] = ["@wuming-town/content-schema"];
