import { defineWorkspaceSmoke, type WorkspaceSmoke } from "@wuming-town/foundation";

export {
  GAME_SESSION_PROJECTION_VERSION,
  MAIN_TO_SIMULATION_MESSAGE_KIND,
  PLAYER_COMMAND_KIND,
  SIMULATION_PROTOCOL_REASON_CODE,
  SIMULATION_TO_MAIN_MESSAGE_KIND,
  SIM_PROTOCOL_VERSION,
  SIM_SCHEMA_VERSION,
} from "./constants";
export {
  sameGameSessionProjectionBasis,
  validateCoherentGameSessionProjectionPair,
  validateGameSessionAlertsV1,
  validateGameSessionProjectionRequest,
  validateGameSessionReadyContract,
  validateGameSessionRenderProjectionV1,
  validateGameSessionUiProjectionV1,
} from "./game-session-projection-validation";
export type {
  GameSessionAlertV1,
  GameSessionAnimationStateV1,
  GameSessionDayPhaseV1,
  GameSessionEntityRefV1,
  GameSessionJobMarkerStateV1,
  GameSessionProjectionBasisV1,
  GameSessionProjectionContractV1,
  GameSessionProjectionRequestV1,
  GameSessionRenderEntityV1,
  GameSessionRenderKindV1,
  GameSessionRenderProjectionV1,
  GameSessionResidentSelectionDetailV1,
  GameSessionResourceKindV1,
  GameSessionResourceSelectionDetailV1,
  GameSessionSelectionBasisV1,
  GameSessionSelectionDetailV1,
  GameSessionStructuredReasonV1,
  GameSessionStructureSelectionDetailV1,
  GameSessionUiJobMarkerV1,
  GameSessionUiProjectionV1,
  GameSessionUiResidentV1,
  GameSessionUiResourceV1,
} from "./game-session-projection";
export type { GameSessionProjectionValidationResult } from "./game-session-projection-validation";
export { validateMainToSimulationMessage } from "./validation";
export type {
  AlertBatchMessage,
  AlertBatchPayload,
  CandidateCounts,
  CellRef,
  CommandBasis,
  CommandBlockedReason,
  CommandBlockedReasonCode,
  CommandJobRef,
  CommandOrderRef,
  CommandResultMessage,
  CommandResultPayload,
  CommandTargetRef,
  DevCommandMessage,
  DevCommandPayload,
  FatalSimulationErrorMessage,
  FatalSimulationErrorPayload,
  InitSessionMessage,
  InitSessionPayload,
  LoadSessionMessage,
  LoadSessionPayload,
  MainMessageValidationResult,
  MainToSimulationMessage,
  MainToSimulationMessageKind,
  MetricsSampleMessage,
  MetricsSamplePayload,
  PauseMessage,
  PausePayload,
  PlayableBuildProjectionV1,
  PlayableCommandTemplateV1,
  PlayableLampProjectionV1,
  PlayableOrderJobProjectionV1,
  PlayablePawnProjectionV1,
  PlayablePlacementProjectionV1,
  PlayableProjectionBasisV1,
  PlayableProjectionV1,
  PlayableResourceCountProjectionV1,
  PlayableResourceProjectionV1,
  PlayableResourceRequirementProjectionV1,
  PlayableTargetActionProjectionV1,
  PlayerCommand,
  PlayerCommandBatchMessage,
  PlayerCommandBatchPayload,
  PlayerCommandKind,
  PlayerCommandPayload,
  PlayerCommandResult,
  PlayerCommandAcceptedResult,
  PlayerCommandRejectedResult,
  ProtocolEnvelope,
  ProtocolEntityRef,
  ProtocolRejection,
  PrioritizeLampWorkCommand,
  PrioritizeLampWorkPayload,
  ReadyMessage,
  ReadyPayload,
  RenderSnapshotMessage,
  RenderSnapshotPayload,
  RequestSaveMessage,
  RequestSavePayload,
  RequestUiDetailMessage,
  RequestUiDetailPayload,
  QueueSimpleBuildCommand,
  QueueSimpleBuildPayload,
  ResourceRequirementRef,
  SaveReadyMessage,
  SaveReadyPayload,
  SetSpeedMessage,
  SetSpeedPayload,
  ShutdownMessage,
  ShutdownPayload,
  SimulationProtocolReasonCode,
  SimulationToMainMessage,
  SimulationToMainMessageKind,
  StaleBasisRef,
  UiDeltaMessage,
  UiDeltaPayload,
  UiDetailSubject,
  PolicyRef,
} from "./types";
export type {
  EntityTaskReadModel,
  EntityInspectorReadModel,
  EntityNeedReadModel,
  ResourceSummaryReadModel,
  StructuredReasonReadModel,
  WorldEntityActivityReadModel,
  WorldFocusMarkerReadModel,
  WorldJobMarkerReadModel,
  WorldSemanticAreaReadModel,
} from "./web-read-model";
export type {
  TerrainKind,
  TileCoordinate,
  WorldJobMarkerState,
  WorldStructuredJobKind,
  TownAlertReadModel,
  WorldEntityActivityState,
  TownOverviewReadModel,
  WorldChunkReadModel,
  WorldEntityKind,
  WorldEntityReadModel,
  WorldFocusMarkerKind,
  WorldReadModel,
  WorldSemanticAreaKind,
} from "./web-read-model";

export const SIM_PROTOCOL_SMOKE: WorkspaceSmoke = defineWorkspaceSmoke(
  "@wuming-town/sim-protocol",
  "package",
);

export const SIM_PROTOCOL_PUBLIC_INPUTS: readonly string[] = ["@wuming-town/content-schema"];
